name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
      - run: raku --version
      - name: Check all scripts compile
        run: |
          for script in *; do
            if [[ -f $script ]]; then
              echo $script
              raku -c $script
            fi
          done
      - name: Run tests
        run: raku t/*.rakutest